######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 18 16:19:19 2011
######################################################################

include($$[QT_INSTALL_DATA]/mkspecs/dcpconfig.pri)
TEMPLATE = app
TARGET = qmtest 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qmsystem2 debug
LIBS += -lqmsystem2
# Input
SOURCES += main.cpp
